{{- if eq .Values.scaleUp true }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "helm-guestbook.fullname" . }}

  {{- if eq .Values.GlobalMinPods true }}
  minReplicas: 2
  {{- else }}
  minReplicas: {{ .Values.replicaCounts }}
  {{- end }}
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu 
        target:
          type: Utilization
          averageUtilization: 25
{{- end }}
